# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'OCWaveView', :git => 'https://github.com/emannuelOC/OCWaveView.git', :tag => '0.0.4'

end
